
###限流
zuul:
  retryable: true
  ratelimit:
    enabled: true
    repository: redis
    behind-proxy: true
    default-policy:
      limit: 5
      quota: 4
      refresh-interval: 10
      type: url

users-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.roger.springcloudFinchley.rules.CustomRule



logging:
  path: /opt/pipeline/logs/gateway
  config: classpath:logback-spring.xml




